export const ACTION_APPLICATION_CHANGE_THEME = 'ACTION_APPLICATION_CHANGE_THEME';
export const ACTION_APPLICATION_SNACKBAR = 'ACTION_APPLICATION_SNACKBAR';
export const ACTION_APPLICATION_LOGIN = 'ACTION_APPLICATION_LOGIN';
export const ACTION_APPLICATION_LOGOUT = 'ACTION_APPLICATION_LOGOUT';